stages:
  - build
  - test
  - validate
  - deploy

default:
  timeout: 15m

.docker:
  image: debian:testing
  variables:
    NO_CLEAR: "yes"
    DOCKER_HOST: "tcp://docker"
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - apt-get update
    - apt-get install -y curl lsb-release
    - curl -fsSL https://deb.nodesource.com/setup_22.x | bash
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable" > /etc/apt/sources.list.d/docker.list
#    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
    - apt-get update
    - apt-get install -y nodejs
    - apt-get install -y  docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - ./setup.sh

build:
  stage: build
  extends: .docker
  script:
    - make dump
    - make build
  artifacts:
    paths:
      - .ovhconfig
      - www

tests-unit:
  stage: test
  extends: .docker
  parallel:
    matrix:
      - target:
        - dump
        - lint
        - frontend-test
  script:
    - make github
    - make $target

tests-unit-with-backend:
  stage: test
  extends: .docker
  parallel:
    matrix:
      - target:
        - backend-test
  script:
    - make github
    - make dependencies
    - make start
    - make $target

tests-e2e:
  stage: test
  extends: .docker
  parallel:
    matrix:
      - flavor:
        - desktop
        - playwright
  script:
    - ./setup.sh
    - make github
    - make dc-build
    - make start
    - make dependencies
    - make integration-test-${flavor}-run
    - make integration-test-${flavor}-styles
  artifacts:
    when: always
    paths:
      - tmp/integration/$flavor

update-e2e:
  stage: test
  extends: .docker
  script:
    - ./setup.sh
    - make github
    - make dc-build
    - make start
    - make dependencies
    - UPDATE=1 make integration-update-playwright
    - git status
  artifacts:
    when: always
    paths:
      - tests/e2e/**/*.png

valid:
  stage: validate
  image: ubuntu:latest
  needs:
    - tests-unit
    - tests-e2e
    - tests-unit-with-backend
  script:
    - echo "ok"

# deploy:
#   stage: deploy
#   environment:
#     name: production
#   rules:
#     - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
#       when: never
#     - when: on_success
#   script:
#     - ./setup.sh
#     - make github
#     - make build
#     - make deploy
#   variables:
#     CRYPTOMEDIC_DEPLOY_WEB_HOST: $CRYPTOMEDIC_DEPLOY_WEB_HOST
#     CRYPTOMEDIC_DEPLOY_WEB_PORT: $CRYPTOMEDIC_DEPLOY_WEB_PORT
#     CRYPTOMEDIC_DEPLOY_WEB_TOKEN: $CRYPTOMEDIC_DEPLOY_WEB_TOKEN
#     CRYPTOMEDIC_DEPLOY_FILES_HOST: $CRYPTOMEDIC_DEPLOY_FILES_HOST
#     CRYPTOMEDIC_DEPLOY_FILES_USER: $CRYPTOMEDIC_DEPLOY_FILES_USER
#     CRYPTOMEDIC_DEPLOY_FILES_PASSWORD: $CRYPTOMEDIC_DEPLOY_FILES_PASSWORD
#   artifacts:
#     when: always
#     paths:
#       - tmp/deploy.log
