language: php

#addons:
#firefox: "40"

# To go on the new infrastructure
# @see http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade
sudo: false

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - mysql -e "show variables like 'max%' " -uroot
  - mysql -e "create database IF NOT EXISTS amd_chakaria;" -uroot
  - mysql -e "GRANT ALL ON *.* TO amd_chakaria@localhost" -uroot
  - mysql -e "SET GLOBAL time_zone = '+00:00'" -uroot
  - bin/prj-install.sh

  - sleep 3 # give xvfb server time to start

script:
  - bin/prj-test.sh

after_failure:
#  - cat rest/storage/log/*
  - find tmp/ -name "*.png"  -exec "bin/travis-upload.sh" "{}" ";"
  - find tmp/ -name "*.json" -exec "bin/travis-upload.sh" "{}" ";"
