language: node_js
node_js:
  - "12"

addons:
  chrome: latest
  firefox: latest

before_install:
    - docker-compose up --quiet-pull --detach

    before_script:
  - npm run reset

script:
  - npm run -s test-api
  - npm run -s test-unit
