os: linux
dist: bionic

language: node_js
node_js:
  - "14"

addons:
  apt:
    packages:
      - make
      - lftp
      - wget
      - openssh-client
      - sshpass
      - sshfs
  chrome: stable
  firefox: latest

before_install:
  - ssh -V
  - sort --version
  - docker-compose --version

install:
  - make setup-computer
  - npm ci
  - touch node_modules/.dependencies
  # Start docker-compose stack
  # This is needed by the install (composer.phar) part
  - make start

script:
  - make test
  - make lint

deploy:
  - provider: script
    script: make deploy
    skip_cleanup: true
    on:
      branch: 
        - master
        - ci/*

after_script:
  - make stop
