language: node_js
node_js:
  - "12"

addons:
  chrome: stable
  firefox: latest

before_install:
  - docker-compose --version
  - docker-compose up -d
  # --quiet-pull --detach

before_script:
  - npm run reset

script:
  - npm run -s test-api
  - npm run -s test-unit
  - npm run -s test-e2e
