dist: bionic

language: node_js
node_js:
  - "12"

addons:
  apt:
    packages:
      - make
      - lftp
      - wget
  chrome: stable
  firefox: latest

before_install:
  - lftp --version
  - docker-compose --version

install:
  # Start docker-compose stack
  # This is needed by the install (composer.phar) part
  - make start

script:
  - make test
  - make lint
  - make deploy-test

deploy:
  - provider: script
    script: make deploy
    skip_cleanup: true
    on:
      branch: 
        - master

after_script:
  - make stop
