language: php

# To go on the new infrastructure
# @see http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade
sudo: false

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - mysql -e "show variables like 'max%' " -uroot
#  - mysql -e "SET GLOBAL max_allowed_packet = 64M;" -uroot
#  - echo -e "[server]\nmax_allowed_packet=64M" | sudo tee -a /etc/mysql/my.cnf
#  - mysql -e "show variables like 'max%' " -uroot
  - mysql -e "create database IF NOT EXISTS amd_chakaria;" -uroot
  - mysql -e "GRANT ALL ON *.* TO amd_chakaria@localhost" -uroot
  - mysql -e "SET GLOBAL time_zone = '+00:00'" -uroot
  - bin/prj-install.sh

#  - npm start > /dev/null &
#  - npm run update-webdriver
  - sleep 3 # give xvfb server time to start

script:
  - bin/prj-test.sh
#  - node_modules/.bin/karma start test/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
#  - node_modules/.bin/protractor test/protractor-conf.js --browser=firefox

after_failure:
#   - cat rest/storage/log/*
