dist: bionic

language: node_js
node_js:
  - "12"

addons:
  apt:
    packages:
      - make
      - wget
      - openssh-client
      - sshpass
  chrome: stable
  firefox: latest

before_install:
  - lftp --version
  - docker-compose --version
  - make init-computer

install:
  # Start docker-compose stack
  # This is needed by the install (composer.phar) part
  - make start

script:
  - make test
  - make lint

deploy:
  - provider: script
    script: make deploy
    skip_cleanup: true
    on:
      branch: 
        - master
        - build/*

after_script:
  - make stop
