version: "3.1"
services:
  server:
    build:
      context: conf/server/
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      IN_DOCKER: server
    expose:
      - 80
    volumes:
      - .:/app

  mysql:
    # https://hub.docker.com/_/mysql/
    # OVH is on 5.5
    image: mysql:5.5
    environment:
      IN_DOCKER: mysql
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cryptomedic
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    expose:
      - 3306

  phpmyadmin:
    # https://hub.docker.com/r/phpmyadmin/phpmyadmin/
    image: phpmyadmin/phpmyadmin
    environment:
      IN_DOCKER: phpmyadmin
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    expose:
       - 80
    depends_on:
      - mysql

  mail:
    # https://hub.docker.com/r/mailhog/mailhog/
    # The WS does not work correctly, due to proxy...
    image: mailhog/mailhog
    environment:
      IN_DOCKER: mail
      MH_UI_WEB_PATH: /xmailx
    expose:
      - 1025
      - 8025

  dev:
    build:
      context: conf/dev
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      IN_DOCKER: dev
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
    volumes:
      - .:/app
    ports:
      - ${CRYPTOMEDIC_PORT:-0}:80 # Only if the variable is not set in the environment
