version: "3.1"
services:
  server:
    build:
      context: conf/server/
      dockerfile: Dockerfile
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
      - PRJ_DIR=/app
      - APACHE_DOCUMENT_ROOT=/app/www
    ports:
      - ${CRYPTOMEDIC_PORT:-5080}:80 # Only if the variable is not set in the environment
    volumes:
      - .:/app

  mysql:
    # https://hub.docker.com/_/mysql/
    # OVH is on 5.5
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cryptomedic
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    expose:
      - 3306

  phpmyadmin:
    # https://hub.docker.com/r/phpmyadmin/phpmyadmin/
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    expose:
       - 80
    depends_on:
      - mysql

  mail:
    # https://hub.docker.com/r/mailhog/mailhog/
    # The WS does not work correctly, due to proxy...
    image: mailhog/mailhog
    environment:
      MH_UI_WEB_PATH: /xmailx
    expose:
      - 1025
      - 8025

