
CREATE TABLE `bill_lines` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL,
  `lastuser` varchar(50) DEFAULT NULL,
  `bill_id` int(10) UNSIGNED NOT NULL,
  `Date` date NULL,
  `ExaminerName` varchar(127) DEFAULT NULL,
  `Amount` decimal NOT NULL DEFAULT 0,
  `Notes` Text NULL,
  PRIMARY KEY (`id`),
  KEY `bill_lines_id` (`bill_id`),
  CONSTRAINT `bill_lines_ibfk_1` FOREIGN KEY (`bill_id`) REFERENCES `bills` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `bill_lines` ADD `type` VARCHAR(32) NOT NULL AFTER `bill_id`;

ALTER TABLE `bill_lines` ADD `title` VARCHAR(128) NOT NULL AFTER `type`;

insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `consult_CDC_consultation_Bengali_Doctor`, 'consult', 'consult_CDC_consultation_Bengali_Doctor' from bills where `consult_CDC_consultation_Bengali_Doctor` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `consult_CDC_consultation_Doctor`, 'consult', 'consult_CDC_consultation_Doctor' from bills where `consult_CDC_consultation_Doctor` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `consult_CDC_consultation_physio`, 'consult', 'consult_CDC_consultation_physio' from bills where `consult_CDC_consultation_physio` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `consult_ClubFoot_Follow_up`, 'consult', 'consult_ClubFoot_Follow_up' from bills where `consult_ClubFoot_Follow_up` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `consult_field_visit`, 'consult', 'consult_field_visit' from bills where `consult_field_visit` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `consult_give_appointment`, 'consult', 'consult_give_appointment' from bills where `consult_give_appointment` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `consult_home_visit`, 'consult', 'consult_home_visit' from bills where `consult_home_visit` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `medecine_calcium_30x500mg`, 'medecine', 'medecine_calcium_30x500mg' from bills where `medecine_calcium_30x500mg` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `medecine_medecine`, 'medecine', 'medecine_medecine' from bills where `medecine_medecine` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `medecine_vitamineD`, 'medecine', 'medecine_vitamineD' from bills where `medecine_vitamineD` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_CMOSH_follow_up`, 'other', 'other_CMOSH_follow_up' from bills where `other_CMOSH_follow_up` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_Other_consultation_care`, 'other', 'other_Other_consultation_care' from bills where `other_Other_consultation_care` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_Other_dressing`, 'other', 'other_Other_dressing' from bills where `other_Other_dressing` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_Other_plaster`, 'other', 'other_Other_plaster' from bills where `other_Other_plaster` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_X_Ray`, 'other', 'other_X_Ray' from bills where `other_X_Ray` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_group_physiotherapy`, 'other', 'other_group_physiotherapy' from bills where `other_group_physiotherapy` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_make_long_plaster`, 'other', 'other_make_long_plaster' from bills where `other_make_long_plaster` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_make_short_plaster`, 'other', 'other_make_short_plaster' from bills where `other_make_short_plaster` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_making_dressing`, 'other', 'other_making_dressing' from bills where `other_making_dressing` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_making_plaster`, 'other', 'other_making_plaster' from bills where `other_making_plaster` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_microbus`, 'other', 'other_microbus' from bills where `other_microbus` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_nutritionalAdvice`, 'other', 'other_nutritionalAdvice' from bills where `other_nutritionalAdvice` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_nutritionalSupport`, 'other', 'other_nutritionalSupport' from bills where `other_nutritionalSupport` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_physiotherapy`, 'other', 'other_physiotherapy' from bills where `other_physiotherapy` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_physiotherapy_adult`, 'other', 'other_physiotherapy_adult' from bills where `other_physiotherapy_adult` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `other_physiotherapy_child`, 'other', 'other_physiotherapy_child' from bills where `other_physiotherapy_child` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_Burn_release`, 'surgical', 'surgical_Burn_release' from bills where `surgical_Burn_release` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_PMR_club_club_foot_bi`, 'surgical', 'surgical_PMR_club_club_foot_bi' from bills where `surgical_PMR_club_club_foot_bi` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_PMR_club_foot`, 'surgical', 'surgical_PMR_club_foot' from bills where `surgical_PMR_club_foot` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_Pin_removal`, 'surgical', 'surgical_Pin_removal' from bills where `surgical_Pin_removal` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_burn_little_release`, 'surgical', 'surgical_burn_little_release' from bills where `surgical_burn_little_release` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_epiphysiodesis`, 'surgical', 'surgical_epiphysiodesis' from bills where `surgical_epiphysiodesis` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_epiphysiodesis_bi`, 'surgical', 'surgical_epiphysiodesis_bi' from bills where `surgical_epiphysiodesis_bi` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_osteotomy`, 'surgical', 'surgical_osteotomy' from bills where `surgical_osteotomy` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_osteotomy_bi`, 'surgical', 'surgical_osteotomy_bi' from bills where `surgical_osteotomy_bi` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_other_operation`, 'surgical', 'surgical_other_operation' from bills where `surgical_other_operation` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_percutaneous_AL_club_foot`, 'surgical', 'surgical_percutaneous_AL_club_foot' from bills where `surgical_percutaneous_AL_club_foot` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_percutaneous_achil_tenotomy_bi_cdc`, 'surgical', 'surgical_percutaneous_achil_tenotomy_bi_cdc' from bills where `surgical_percutaneous_achil_tenotomy_bi_cdc` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_percutaneous_achil_tenotomy_bi_cmosh`, 'surgical', 'surgical_percutaneous_achil_tenotomy_bi_cmosh' from bills where `surgical_percutaneous_achil_tenotomy_bi_cmosh` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_percutaneous_achil_tenotomy_uni_cdc`, 'surgical', 'surgical_percutaneous_achil_tenotomy_uni_cdc' from bills where `surgical_percutaneous_achil_tenotomy_uni_cdc` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_polio_AL`, 'surgical', 'surgical_polio_AL' from bills where `surgical_polio_AL` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `surgical_polio_achileus_Achileus_lenthening_bi`, 'surgical', 'surgical_polio_achileus_Achileus_lenthening_bi' from bills where `surgical_polio_achileus_Achileus_lenthening_bi` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_AFO_-_Articulated`, 'workshop', 'workshop_AFO_-_Articulated' from bills where `workshop_AFO_-_Articulated` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_AFO_night`, 'workshop', 'workshop_AFO_night' from bills where `workshop_AFO_night` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_AFO_walking`, 'workshop', 'workshop_AFO_walking' from bills where `workshop_AFO_walking` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Abdominal_corset_belt`, 'workshop', 'workshop_Abdominal_corset_belt' from bills where `workshop_Abdominal_corset_belt` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Arch_support`, 'workshop', 'workshop_Arch_support' from bills where `workshop_Arch_support` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Artificial_Tr_radial_prosthesis_Alimco`, 'workshop', 'workshop_Artificial_Tr_radial_prosthesis_Alimco' from bills where `workshop_Artificial_Tr_radial_prosthesis_Alimco` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Artificial_Tr_radial_prosthesis_jaipur`, 'workshop', 'workshop_Artificial_Tr_radial_prosthesis_jaipur' from bills where `workshop_Artificial_Tr_radial_prosthesis_jaipur` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Artificial_limb_-_AK_-_Exoskeleton`, 'workshop', 'workshop_Artificial_limb_-_AK_-_Exoskeleton' from bills where `workshop_Artificial_limb_-_AK_-_Exoskeleton` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Artificial_limb_-_AK_-_single_axis_standard`, 'workshop', 'workshop_Artificial_limb_-_AK_-_single_axis_standard' from bills where `workshop_Artificial_limb_-_AK_-_single_axis_standard` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Artificial_limb_-_BK_-_Endoskeleton_with_pylon_Std`, 'workshop', 'workshop_Artificial_limb_-_BK_-_Endoskeleton_with_pylon_Std' from bills where `workshop_Artificial_limb_-_BK_-_Endoskeleton_with_pylon_Std` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Artificial_limb_-_BK_-_Exoskeleton`, 'workshop', 'workshop_Artificial_limb_-_BK_-_Exoskeleton' from bills where `workshop_Artificial_limb_-_BK_-_Exoskeleton` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_BAFO_night`, 'workshop', 'workshop_BAFO_night' from bills where `workshop_BAFO_night` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_BAFO_walking`, 'workshop', 'workshop_BAFO_walking' from bills where `workshop_BAFO_walking` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_BHKAFO_Drop_lock_single_axis`, 'workshop', 'workshop_BHKAFO_Drop_lock_single_axis' from bills where `workshop_BHKAFO_Drop_lock_single_axis` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_BHKAFO_night`, 'workshop', 'workshop_BHKAFO_night' from bills where `workshop_BHKAFO_night` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_BHKAFO_walking`, 'workshop', 'workshop_BHKAFO_walking' from bills where `workshop_BHKAFO_walking` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_BKAFO_night_-_plastic`, 'workshop', 'workshop_BKAFO_night_-_plastic' from bills where `workshop_BKAFO_night_-_plastic` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_BKAFO_walking`, 'workshop', 'workshop_BKAFO_walking' from bills where `workshop_BKAFO_walking` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_CP_chair_-_wooden`, 'workshop', 'workshop_CP_chair_-_wooden' from bills where `workshop_CP_chair_-_wooden` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_CP_standing_table_-_wooden`, 'workshop', 'workshop_CP_standing_table_-_wooden' from bills where `workshop_CP_standing_table_-_wooden` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Cervical_Collar`, 'workshop', 'workshop_Cervical_Collar' from bills where `workshop_Cervical_Collar` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Compensation_sole`, 'workshop', 'workshop_Compensation_sole' from bills where `workshop_Compensation_sole` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Crutch_-_Stainless_steel`, 'workshop', 'workshop_Crutch_-_Stainless_steel' from bills where `workshop_Crutch_-_Stainless_steel` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Crutch_a_pair_-_local`, 'workshop', 'workshop_Crutch_a_pair_-_local' from bills where `workshop_Crutch_a_pair_-_local` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_DB_splint`, 'workshop', 'workshop_DB_splint' from bills where `workshop_DB_splint` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Elbow_crutch`, 'workshop', 'workshop_Elbow_crutch' from bills where `workshop_Elbow_crutch` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Extension_brace_-_AFO`, 'workshop', 'workshop_Extension_brace_-_AFO' from bills where `workshop_Extension_brace_-_AFO` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Finger_splint`, 'workshop', 'workshop_Finger_splint' from bills where `workshop_Finger_splint` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Hand_splint`, 'workshop', 'workshop_Hand_splint' from bills where `workshop_Hand_splint` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Hearing_aids`, 'workshop', 'workshop_Hearing_aids' from bills where `workshop_Hearing_aids` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_KAFO_night`, 'workshop', 'workshop_KAFO_night' from bills where `workshop_KAFO_night` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Knee_brace`, 'workshop', 'workshop_Knee_brace' from bills where `workshop_Knee_brace` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Lifspring_BAFO`, 'workshop', 'workshop_Lifspring_BAFO' from bills where `workshop_Lifspring_BAFO` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Matetarsal_pade`, 'workshop', 'workshop_Matetarsal_pade' from bills where `workshop_Matetarsal_pade` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Orthoshoes_with_bar_-_one_leg`, 'workshop', 'workshop_Orthoshoes_with_bar_-_one_leg' from bills where `workshop_Orthoshoes_with_bar_-_one_leg` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Orthoshoes_without_bar_-_one_leg`, 'workshop', 'workshop_Orthoshoes_without_bar_-_one_leg' from bills where `workshop_Orthoshoes_without_bar_-_one_leg` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Other_orthodevice`, 'workshop', 'workshop_Other_orthodevice' from bills where `workshop_Other_orthodevice` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Reparing`, 'workshop', 'workshop_Reparing' from bills where `workshop_Reparing` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Supinator_corner`, 'workshop', 'workshop_Supinator_corner' from bills where `workshop_Supinator_corner` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_UHKAFO_-_Drop_lock_single_axis_-_MI`, 'workshop', 'workshop_UHKAFO_-_Drop_lock_single_axis_-_MI' from bills where `workshop_UHKAFO_-_Drop_lock_single_axis_-_MI` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_UHKAFO_night`, 'workshop', 'workshop_UHKAFO_night' from bills where `workshop_UHKAFO_night` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_UHKAFO_walking`, 'workshop', 'workshop_UHKAFO_walking' from bills where `workshop_UHKAFO_walking` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_UKAFO_walking`, 'workshop', 'workshop_UKAFO_walking' from bills where `workshop_UKAFO_walking` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Walker_with_wheel_-_folding`, 'workshop', 'workshop_Walker_with_wheel_-_folding' from bills where `workshop_Walker_with_wheel_-_folding` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Walker_with_wheel_-_non_folding`, 'workshop', 'workshop_Walker_with_wheel_-_non_folding' from bills where `workshop_Walker_with_wheel_-_non_folding` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Wheel_Chair_-_china_-_modified`, 'workshop', 'workshop_Wheel_Chair_-_china_-_modified' from bills where `workshop_Wheel_Chair_-_china_-_modified` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Wheel_chair_-_folding`, 'workshop', 'workshop_Wheel_chair_-_folding' from bills where `workshop_Wheel_chair_-_folding` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_White_can`, 'workshop', 'workshop_White_can' from bills where `workshop_White_can` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_Wirst_splint`, 'workshop', 'workshop_Wirst_splint' from bills where `workshop_Wirst_splint` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_artificial_limb_-_AK_-_polycentric_knee_joint`, 'workshop', 'workshop_artificial_limb_-_AK_-_polycentric_knee_joint' from bills where `workshop_artificial_limb_-_AK_-_polycentric_knee_joint` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_crutch_alumenium_-_a_pair`, 'workshop', 'workshop_crutch_alumenium_-_a_pair' from bills where `workshop_crutch_alumenium_-_a_pair` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_fracture_brace_-_one_leg`, 'workshop', 'workshop_fracture_brace_-_one_leg' from bills where `workshop_fracture_brace_-_one_leg` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_leg_truction`, 'workshop', 'workshop_leg_truction' from bills where `workshop_leg_truction` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_lifspring_afo`, 'workshop', 'workshop_lifspring_afo' from bills where `workshop_lifspring_afo` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_mailwalke_brace`, 'workshop', 'workshop_mailwalke_brace' from bills where `workshop_mailwalke_brace` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_samainto_brace`, 'workshop', 'workshop_samainto_brace' from bills where `workshop_samainto_brace` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_smo`, 'workshop', 'workshop_smo' from bills where `workshop_smo` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_thoracic_brace`, 'workshop', 'workshop_thoracic_brace' from bills where `workshop_thoracic_brace` > 0;
insert into bill_lines(created_at, updated_at, lastuser, bill_id, Date, ExaminerName, Amount, `type`, `title`) select created_at, updated_at, lastuser, id, Date,ExaminerName,  `workshop_wheel_chair_china`, 'workshop', 'workshop_wheel_chair_china' from bills where `workshop_wheel_chair_china` > 0;

ALTER TABLE `bill_lines` DROP `type`;
