#!/usr/bin/env bash

set -o errexit
set -o pipefail

# shellcheck source=../../bin/cr-lib
. "$(dirname "${BASH_SOURCE[0]}")"/../../bin/cr-lib

cr-ensure-started

header_begin "get test"
cr-get-config "test"
echo ""
RES="$(cr-get-config "test")"
if [[ "$RES" != "hello world" ]]; then
    echo "Unexpected: $RES"
    exit 1
fi
header_end

header_begin "get in.there"
cr-get-config "in.there"
echo ""
RES="$(cr-get-config "in.there")"
if [[ "$RES" != "hello universe" ]]; then
    echo "Unexpected: $RES"
    exit 1
fi
header_end

echo "Test successfull"
