update bills set ExaminerName = 'Murshed' where examinerName = 'MUR/ERS';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/DR MONIR';
update bills set ExaminerName = 'Murshed' where examinerName = 'MUR/REZ/RIC';
update bills set ExaminerName = 'Hassan 2' where examinerName = 'HASAN';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIC+BP';
update bills set ExaminerName = 'Liton' where examinerName = 'LITON';
update bills set ExaminerName = 'Murshed' where examinerName = 'MUR/NUR';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/RIC';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIC/RUK';
update bills set ExaminerName = 'Taslim' where examinerName = 'TC/SHE/EAR/RIC';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIC+SHE';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/REZ';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/MUR';
update bills set ExaminerName = 'Murshed' where examinerName = 'MUR-NUR';
update bills set ExaminerName = 'Nur Alam' where examinerName = 'Nur Alam';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'DR Bp REZ';
update bills set ExaminerName = 'Monir' where examinerName = 'Dr MONIR / SHE';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS+RAZ';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/SHE';
update bills set ExaminerName = 'Rina' where examinerName = 'RINA';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/RIC/Dr VC';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/DrJG';
update bills set ExaminerName = 'Murshed' where examinerName = 'MUR/PRI';
update bills set ExaminerName = 'Debashish' where examinerName = 'DEV';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIC+TC+MU+SHE+ER';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIC/GP';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'BP/MUR';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS+RIC';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/RAZ';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/DR BP';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/RAZ';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'Dr GP';
update bills set ExaminerName = 'Hassan 1' where examinerName = 'AHSAN';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/CARI';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIC+TAS+ERS+REZ';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIC/TH/SHE';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIC/SHE/JG/MO';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/DRJG/MUR';
update bills set ExaminerName = 'Monir' where examinerName = 'Dr MO+SHE+RIC';
update bills set ExaminerName = 'Taslim' where examinerName = 'Dr TOSLIM REZ';
update bills set ExaminerName = 'Monir' where examinerName = 'MONIR/SHE';
update bills set ExaminerName = 'Murshed' where examinerName = 'MUR/ER/PRI';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'Dr LOR/RIC/SHE';
update bills set ExaminerName = 'Monir' where examinerName = 'Dr MONIR/MUR';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'VC/CM/MUR/ERS/RIC';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIK+SHE+REZ+MUR+ERS';
update bills set ExaminerName = 'Debashish' where examinerName = 'Debashish';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'JG/SHE/MUR';
update bills set ExaminerName = 'Monir' where examinerName = 'Dr MONIR/SHE';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'TC/MUR/SHE';
update bills set ExaminerName = 'Monir' where examinerName = 'Dr MONI/MUR/ERS/RIC';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'TC/MUR/RIC';
update bills set ExaminerName = 'Shetou' where examinerName = 'SH/RA/RI/Drm';
update bills set ExaminerName = 'Kobir' where examinerName = 'KOB';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/RA/Dr';
update bills set ExaminerName = 'Murshed' where examinerName = 'MUR-PRI-ER';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'GP+SHE+ERS+MUR';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIK+RUK';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIC+RAZ+SHE';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/CAR';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'Gİrard';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE-RIC-REZ';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/ERS/MUR/RIC';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'Thierry';
update bills set ExaminerName = 'Rezaul' where examinerName = 'REZ+SHE+ERS+D';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'BP/ERS/SHE';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/RIC';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/EAR/RAZ';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'GP/RIC/REZ';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIC+FC+SHE+ER';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS:MUR';
update bills set ExaminerName = 'Rezaul' where examinerName = 'REZ/Dr TASLIM';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/EAR/Dr MO';
update bills set ExaminerName = 'Rezaul' where examinerName = 'REZ/SHE';
update bills set ExaminerName = 'Murshed' where examinerName = 'MUR/SHE/RIC/ERS/TAS';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/RIC/TAS';
update bills set ExaminerName = 'Taslim' where examinerName = 'TAS/REZ';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/KOB';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'FRANCK';
update bills set ExaminerName = 'Murshed' where examinerName = 'MUR-PRI';
update bills set ExaminerName = 'Taslim' where examinerName = 'TH/REZ';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'TC/RIC/SHE/ERS';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS+MUR';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/PRI';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS+PRE';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIC+TC+MU+SHE+ERri';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'BP/MUR/ERS/RIC';
update bills set ExaminerName = 'Taslim' where examinerName = 'Dr TOSLIM';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIC/JG';
update bills set ExaminerName = 'Monir' where examinerName = 'MONIR/MUR/SHE';
update bills set ExaminerName = 'Ershad' where examinerName = 'ER/PRI';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/DEV';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/PRE';
update bills set ExaminerName = 'Monir' where examinerName = 'Monir';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIC+GP+MU+SHE+ER';
update bills set ExaminerName = 'Rezaul' where examinerName = 'REZ-ERS';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/RIC/ERS/REZ';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/REZ/ERS';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'Dr TH/SHE';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS+REZ';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/TAS/RIC';
update bills set ExaminerName = 'Murshed' where examinerName = 'MUR-RIC-PRI';
update bills set ExaminerName = 'Murshed' where examinerName = 'MUR/RUK';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'CM/MUR/ERS';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS+SHA';
update bills set ExaminerName = 'Monir' where examinerName = 'Dr MONIR/MUR/SHE';
update bills set ExaminerName = 'Hassan 1' where examinerName = 'AHASAN';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/ERS/Dr MO';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/GP';
update bills set ExaminerName = 'Taslim' where examinerName = 'DR TOSLIM/SHE';
update bills set ExaminerName = 'Taslim' where examinerName = 'Dr TOSLIM/ REZ';
update bills set ExaminerName = 'Murshed' where examinerName = 'MUR/RIC/PRI';
update bills set ExaminerName = 'Murshed' where examinerName = 'MUR/RIC';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIC+RUK';
update bills set ExaminerName = 'Ricta' where examinerName = 'RIK+SHE';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS-MUR';
update bills set ExaminerName = 'Taslim' where examinerName = 'TAS/ERS';
update bills set ExaminerName = 'Murshed' where examinerName = 'MUR:NUR';
update bills set ExaminerName = 'Murshed' where examinerName = 'Mur/Raz';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS+CAR';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS+REZ+TAS';
update bills set ExaminerName = 'Ershad' where examinerName = 'REZ Dr TOSLIM';
update bills set ExaminerName = 'Taslim' where examinerName = 'Tas/Ers/Ric';
update bills set ExaminerName = 'Ershad' where examinerName = 'ER/HAS';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS+MUR+CAR';
update bills set ExaminerName = 'Murshed' where examinerName = 'MUR/DEB';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/DAB';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/HAS';
update bills set ExaminerName = 'Murshed' where examinerName = 'MUR:PRI';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/DAV';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'bp';
update bills set ExaminerName = 'Taslim' where examinerName = 'TES/ERS';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS+RIC+TASLIM';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'DAVE';
update bills set ExaminerName = 'Murshed' where examinerName = 'Mur+Raz';
update bills set ExaminerName = 'Shetou' where examinerName = 'SHE/DEB';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'TC/MUR/ERS';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'BP/REZ';
update bills set ExaminerName = 'Murshed' where examinerName = 'Mur+Ers';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/RINA';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'DEV/LITON';
update bills set ExaminerName = 'Rezaul' where examinerName = 'Raz+Mur';
update bills set ExaminerName = 'Rezaul' where examinerName = 'rREZ';
update bills set ExaminerName = 'Taslim' where examinerName = 'Dr TASLIM';
update bills set ExaminerName = 'Debashish' where examinerName = 'DEVASHISH';
update bills set ExaminerName = 'Taslim' where examinerName = 'Tas/Ers/Ric/';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'HANIF';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'REX';
update bills set ExaminerName = 'Hassan 2' where examinerName = 'HASAN/DEV';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/*SHE';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'N';
update bills set ExaminerName = 'Ershad' where examinerName = 'Ers+She';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'TH/ERS/MUR';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'M';
update bills set ExaminerName = 'Ershad' where examinerName = 'ERS/RIC/ZIA';
update bills set ExaminerName = 'Ricta' where examinerName = 'Ric/Ers';
update bills set ExaminerName = 'AMD doctor' where examinerName = 'TC';
