ALTER TABLE `surgeries` DROP `ReportDate`;
ALTER TABLE `surgeries` DROP `PASurgeon`;
ALTER TABLE `surgeries` DROP `PAOk`;
ALTER TABLE `surgeries` DROP `BTCough`;
ALTER TABLE `surgeries` DROP `BTSkin`;
ALTER TABLE `surgeries` DROP `BTTempF`;
ALTER TABLE `surgeries` DROP `NeedTreatment`;
ALTER TABLE `surgeries` DROP `OkForSurgery`;
ALTER TABLE `surgeries` DROP `RadiologicalExam`;
ALTER TABLE `surgeries` DROP `Worms`;
ALTER TABLE `surgeries` DROP FOREIGN KEY  `surgeries_ibfk_10` ; ALTER TABLE `surgeries` DROP `MouthAndTeeth`;
ALTER TABLE `surgeries` DROP FOREIGN KEY  `surgeries_ibfk_9` ; ALTER TABLE `surgeries` DROP `Skin`;
ALTER TABLE `surgeries` DROP FOREIGN KEY  `surgeries_ibfk_8` ; ALTER TABLE `surgeries` DROP `ChestAuscultation`;
ALTER TABLE `surgeries` DROP FOREIGN KEY  `surgeries_ibfk_7` ; ALTER TABLE `surgeries` DROP `HeartAuscultation`;
ALTER TABLE `surgeries` DROP `BloodPresureL`;
ALTER TABLE `surgeries` DROP `BloodPresureH`;
ALTER TABLE `surgeries` DROP `Pulsemin`;
ALTER TABLE `surgeries` DROP `TemperatureF`;
ALTER TABLE `surgeries` DROP `BleedingExecive`;
ALTER TABLE `surgeries` DROP FOREIGN KEY  `surgeries_ibfk_5` ; ALTER TABLE `surgeries` DROP `MedicalProblem`;
ALTER TABLE `surgeries` DROP `TransferChittagong`;
ALTER TABLE `surgeries` DROP `Lastrevisiondate`;
ALTER TABLE `surgeries` DROP `Complication`;
ALTER TABLE `surgeries` DROP `Surgeon`;
ALTER TABLE `surgeries` DROP `Notes`;
ALTER TABLE `surgeries` DROP FOREIGN KEY surgeries_ibfk_6; ALTER TABLE `surgeries` DROP `GeneralCondition`;
ALTER TABLE `surgeries` DROP `Treatment`;
ALTER TABLE `surgeries` DROP `ReportProcedure`;

ALTER TABLE `surgeries` DROP FOREIGN KEY surgeries_ibfk_2; ALTER TABLE `surgeries` DROP `Operation`;
ALTER TABLE `surgeries` DROP FOREIGN KEY surgeries_ibfk_3; ALTER TABLE `surgeries` DROP `Location`;
ALTER TABLE `surgeries` DROP FOREIGN KEY surgeries_ibfk_4; ALTER TABLE `surgeries` DROP `Side`;
ALTER TABLE `surgeries` DROP `Weight`;
ALTER TABLE `surgeries` DROP `Heightcm`;