
-- == club foots == --
ALTER TABLE `club_foots` DROP FOREIGN KEY `club_foots_ibfk_1`;
ALTER TABLE `club_foots` DROP FOREIGN KEY `club_foots_ibfk_2`;
ALTER TABLE `club_foots` DROP `SchoolClass`;
ALTER TABLE `club_foots` DROP `MUAC`;
ALTER TABLE `club_foots` DROP `Walking`;
ALTER TABLE `club_foots` DROP `Sport`;
ALTER TABLE `club_foots` DROP `JumpingReception`;
ALTER TABLE `club_foots` DROP `Adduction`;
ALTER TABLE `club_foots` DROP `HindFootAngleD`;
ALTER TABLE `club_foots` DROP `ThighFoot`;
ALTER TABLE `club_foots` DROP `ThighFootAngle`;
ALTER TABLE `club_foots` DROP `SupinationMax`;
ALTER TABLE `club_foots` DROP `PronationMax`;
ALTER TABLE `club_foots` DROP `EquinusReduc`;
ALTER TABLE `club_foots` DROP `VarusReduc`;
ALTER TABLE `club_foots` DROP `CPBRotation`;
ALTER TABLE `club_foots` DROP `CavusFoot`;
ALTER TABLE `club_foots` DROP `AbnormalMuscle`;
ALTER TABLE `club_foots` DROP `DeepPosteriorCrease`;
ALTER TABLE `club_foots` DROP `DeepMedialCrease`;
ALTER TABLE `club_foots` DROP `DIMEGLIO`;
ALTER TABLE `club_foots` DROP `Run`;
ALTER TABLE `club_foots` DROP `Pain`;
ALTER TABLE `club_foots` DROP `JumpingOneLeg`;
ALTER TABLE `club_foots` DROP `Side`;
ALTER TABLE `club_foots` DROP `WalkingFloorContact`;
ALTER TABLE `club_foots` DROP `WalkingFirstContact`;
ALTER TABLE `club_foots` DROP `AdductionAngle`;
ALTER TABLE `club_foots` DROP `HindFootAngleW`;
ALTER TABLE `club_foots` DROP `DorsalFlexionMax`;
ALTER TABLE `club_foots` DROP `AdductionReduc`;
ALTER TABLE `club_foots` DROP `PlantarFlexionMax`;
   
ALTER TABLE `nonricket_consults` DROP `SchoolClass`;
ALTER TABLE `nonricket_consults` DROP FOREIGN KEY nonricket_consults_ibfk_4; ALTER TABLE `nonricket_consults` DROP `Pathology`;
ALTER TABLE `nonricket_consults` DROP `Comment`;
ALTER TABLE `nonricket_consults` DROP `Undernutrited`;
ALTER TABLE `nonricket_consults` DROP `Physiotherapy61`;
ALTER TABLE `nonricket_consults` DROP FOREIGN KEY nonricket_consults_ibfk_7; ALTER TABLE `nonricket_consults` DROP `Plaster62`;
ALTER TABLE `nonricket_consults` DROP FOREIGN KEY nonricket_consults_ibfk_8; ALTER TABLE `nonricket_consults` DROP `Orthopedicdevice65`;
ALTER TABLE `nonricket_consults` DROP `Worms`;

ALTER TABLE `ricket_consults` DROP `HeightcmLying`;
ALTER TABLE `ricket_consults` DROP `Sittingheightcm`;
ALTER TABLE `ricket_consults` DROP `Ageofbeginningofthedeformitiesyear`;
ALTER TABLE `ricket_consults` DROP `Treatmenttaken`;
ALTER TABLE `ricket_consults` DROP `Worms`;
ALTER TABLE `ricket_consults` DROP `Moneygivenbythefamily`;
ALTER TABLE `ricket_consults` DROP `Undernutrited`;
ALTER TABLE `ricket_consults` DROP `conclusion_medical_other`;
ALTER TABLE `ricket_consults` DROP FOREIGN KEY ricket_consults_ibfk_9; ALTER TABLE `ricket_consults` DROP `Onebowlvegetables`;
ALTER TABLE `ricket_consults` DROP FOREIGN KEY ricket_consults_ibfk_10; ALTER TABLE `ricket_consults` DROP `Twospoonsesamseedgrounded`;
ALTER TABLE `ricket_consults` DROP FOREIGN KEY ricket_consults_ibfk_8; ALTER TABLE `ricket_consults` DROP `Ricewithchun`;
ALTER TABLE `ricket_consults` DROP FOREIGN KEY ricket_consults_ibfk_11; ALTER TABLE `ricket_consults` DROP `Littlefishbowl`;
ALTER TABLE `ricket_consults` DROP FOREIGN KEY ricket_consults_ibfk_12; ALTER TABLE `ricket_consults` DROP `Milkglass`;
ALTER TABLE `ricket_consults` DROP FOREIGN KEY ricket_consults_ibfk_17; ALTER TABLE `ricket_consults` DROP `Bossingforehead`;
ALTER TABLE `ricket_consults` DROP `Cubitusvarus`;
ALTER TABLE `ricket_consults` DROP `KneeMobilityE`;
ALTER TABLE `ricket_consults` DROP `Iodisedsalt`;
ALTER TABLE `ricket_consults` DROP `SchoolClass`;
ALTER TABLE `ricket_consults` DROP FOREIGN KEY ricket_consults_ibfk_22; ALTER TABLE `ricket_consults` DROP `Nutritionaladvice`;
ALTER TABLE `ricket_consults` DROP `KneeMobilityF`;
ALTER TABLE `ricket_consults` DROP `Medical`;
ALTER TABLE `ricket_consults` DROP `conclusion_medical_codLiverOil`;

ALTER TABLE `surgeries` DROP `ReportDate`;
ALTER TABLE `surgeries` DROP `PASurgeon`;
ALTER TABLE `surgeries` DROP `PAOk`;
ALTER TABLE `surgeries` DROP `BTCough`;
ALTER TABLE `surgeries` DROP `BTSkin`;
ALTER TABLE `surgeries` DROP `BTTempF`;
ALTER TABLE `surgeries` DROP `NeedTreatment`;
ALTER TABLE `surgeries` DROP `OkForSurgery`;
ALTER TABLE `surgeries` DROP `RadiologicalExam`;
ALTER TABLE `surgeries` DROP `Worms`;
ALTER TABLE `surgeries` DROP FOREIGN KEY  `surgeries_ibfk_10` ; ALTER TABLE `surgeries` DROP `MouthAndTeeth`;
ALTER TABLE `surgeries` DROP FOREIGN KEY  `surgeries_ibfk_9` ; ALTER TABLE `surgeries` DROP `Skin`;
ALTER TABLE `surgeries` DROP FOREIGN KEY  `surgeries_ibfk_8` ; ALTER TABLE `surgeries` DROP `ChestAuscultation`;
ALTER TABLE `surgeries` DROP FOREIGN KEY  `surgeries_ibfk_7` ; ALTER TABLE `surgeries` DROP `HeartAuscultation`;
ALTER TABLE `surgeries` DROP `BloodPresureL`;
ALTER TABLE `surgeries` DROP `BloodPresureH`;
ALTER TABLE `surgeries` DROP `Pulsemin`;
ALTER TABLE `surgeries` DROP `TemperatureF`;
ALTER TABLE `surgeries` DROP `BleedingExecive`;
ALTER TABLE `surgeries` DROP FOREIGN KEY  `surgeries_ibfk_5` ; ALTER TABLE `surgeries` DROP `MedicalProblem`;
ALTER TABLE `surgeries` DROP `TransferChittagong`;
ALTER TABLE `surgeries` DROP `Lastrevisiondate`;
ALTER TABLE `surgeries` DROP `Complication`;
ALTER TABLE `surgeries` DROP `Surgeon`;
ALTER TABLE `surgeries` DROP `Notes`;
ALTER TABLE `surgeries` DROP FOREIGN KEY surgeries_ibfk_6; ALTER TABLE `surgeries` DROP `GeneralCondition`;
ALTER TABLE `surgeries` DROP `Treatment`;
ALTER TABLE `surgeries` DROP `ReportProcedure`;
