-- == club foots == --
ALTER TABLE `club_foots` DROP FOREIGN KEY `club_foots_ibfk_1`;
ALTER TABLE `club_foots` DROP FOREIGN KEY `club_foots_ibfk_2`;
ALTER TABLE `club_foots` DROP `SchoolClass`;
ALTER TABLE `club_foots` DROP `MUAC`;
ALTER TABLE `club_foots` DROP `Walking`;
ALTER TABLE `club_foots` DROP `Sport`;
ALTER TABLE `club_foots` DROP `JumpingReception`;
ALTER TABLE `club_foots` DROP `Adduction`;
ALTER TABLE `club_foots` DROP `HindFootAngleD`;
ALTER TABLE `club_foots` DROP `ThighFoot`;
ALTER TABLE `club_foots` DROP `ThighFootAngle`;
ALTER TABLE `club_foots` DROP `SupinationMax`;
ALTER TABLE `club_foots` DROP `PronationMax`;
ALTER TABLE `club_foots` DROP `EquinusReduc`;
ALTER TABLE `club_foots` DROP `VarusReduc`;
ALTER TABLE `club_foots` DROP `CPBRotation`;
ALTER TABLE `club_foots` DROP `CavusFoot`;
ALTER TABLE `club_foots` DROP `AbnormalMuscle`;
ALTER TABLE `club_foots` DROP `DeepPosteriorCrease`;
ALTER TABLE `club_foots` DROP `DeepMedialCrease`;
ALTER TABLE `club_foots` DROP `DIMEGLIO`;
ALTER TABLE `club_foots` DROP `Run`;
ALTER TABLE `club_foots` DROP `Pain`;
ALTER TABLE `club_foots` DROP `JumpingOneLeg`;
ALTER TABLE `club_foots` DROP `Side`;
ALTER TABLE `club_foots` DROP `WalkingFloorContact`;
ALTER TABLE `club_foots` DROP `WalkingFirstContact`;
ALTER TABLE `club_foots` DROP `AdductionAngle`;
ALTER TABLE `club_foots` DROP `HindFootAngleW`;
ALTER TABLE `club_foots` DROP `DorsalFlexionMax`;
ALTER TABLE `club_foots` DROP `AdductionReduc`;
ALTER TABLE `club_foots` DROP `PlantarFlexionMax`;
